[package]
name = "identicon"
version = "0.1.1"
authors = ["David Graham <david.malcom.graham@gmail.com>"]
description = "A port of GitHub's identicon algorithm to Rust."
repository = "https://github.com/dgraham/identicon"
license = "MIT"

[lib]
name = "identicon"

[dependencies]
image = "~0.13"
openssl = "~0.9"

[[bin]]
name = "identicon"
