[package]
name = "identicon"
version = "0.0.3"
authors = ["David Graham <david.malcom.graham@gmail.com>"]
description = "A port of GitHub's identicon algorithm to Rust."
repository = "https://github.com/dgraham/identicon"
license = "MIT"

[lib]
name = "identicon"

[dependencies]
image = "~0.2"
openssl = "~0.2"

[[bin]]
name = "identicon"
test = false
doc = false
